version: '2'
services:
    northmuse-app:
        image: northmuse
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://northmuse-mysql:3306/northmuse?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    northmuse-mysql:
        extends:
            file: mysql.yml
            service: northmuse-mysql
